spring:
  application:
    name: application-ms
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 312710
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        ddl-auto: none
        format_sql: true

      javax:
        persistence:
          validation:
            mode: none
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
springdoc:
  swagger-ui.disable-swagger-default-url: true

eureka:
  instance:
    appname: application-ms
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: //
    registryFetchIntervalSeconds: 5
    healthcheck:
      enabled: true

